### ISSUE TITLE
Would really appreciate notes on use of this panzer support

### ISSUE THREAD

**Issue by mhminai** [msprev/dot-panzer#1]
Hello msprev,
Great job with panzer. I am trying to use your dot-panzer and have managed to get a little bit done. It would be very helpful for noobs (like me) if you could just add a statement for the scripts etc. you have in this directory.
I am willing to start off a little modification of the README, if you are okay with having a look at it? Do you have any "pull-request" guidelines for this repo? I ask because this is like an addendum to the main panzer repo. As a new user I can tell you that almost invariably new users would clone this directory and a few helping hints would be useul.

**Comment by msprev** [comment]
Thanks! I'd really appreciate that. Any PRs would be welcome! The documentation for this repository is woefully inadequate.

Just to say that these are my personal `.panzer` files, and they have some quirks that are specific to my workflow (as well as some code that could be cleaner). What I would like is to evolve this into a generic panzer/pandoc 'starter kit' that is decoupled from these quirks. New users could clone this repository, add `style: Article` and get going. What you suggest would be a great step in that direction.

**Comment by jgclark** [comment]
This is related, at least in its title. 
I've cloned this and tried to start using a few of your scripts, particularly `latexmk.py`, `open-pdf.py`, `rmlatex.py`. There's a common line in the imports:
`    sys.path.append(os.path.join(os.environ['PANZER_SHARED'], 'python'))`
This PANZER_SUPPORT isn't mentioned in the documentation. My guess is it might want to be `~/.panzer`, and that's what I've got it set as.

I particularly ask because I can't get your `postflight\latexmk\latexmk.py` to work. When I try it as part of panzer I get this debug log:
```
…
         ----- document style -----
         style:
           General
         full hierarchy:
           Base, General
         writer:
           latex
         ----- run list -----
         postflight:
           1 ~/.panzer/postflight/latexmk/latexmk.py
           2 ~/.panzer/postflight/open_pdf/open_pdf.py
         ----- pandoc write -----
         pandoc writing with options:
           --standalone --include-in-header=jgc-general.sty
         ----- postflight -----
          [1/2] /Users/jonathan/.panzer/postflight/latexmk/latexmk.py
           changed working directory to "/Users/jonathan/Dropbox/m/panzer-testing"
           running "latexmk -f -silent -pdf _talk-test_.tex"
           restored working directory to "/Users/jonathan/Dropbox/m/panzer-testing"
ERROR:     !Traceback (most recent call last):
ERROR:     !  File "/Users/jonathan/.panzer/postflight/latexmk/latexmk.py", line 63, in run_latexmk
ERROR:     !    env=my_env)
ERROR:     !  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
ERROR:     !    restore_signals, start_new_session)
ERROR:     !  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
ERROR:     !    raise child_exception_type(errno_num, err_msg, err_filename)
ERROR:     !FileNotFoundError: [Errno 2] No such file or directory: 'latexmk': 'latexmk'
ERROR:     !During handling of the above exception, another exception occurred:
ERROR:     !Traceback (most recent call last):
ERROR:     !  File "/Users/jonathan/.panzer/postflight/latexmk/latexmk.py", line 114, in <module>
ERROR:     !    main()
ERROR:     !  File "/Users/jonathan/.panzer/postflight/latexmk/latexmk.py", line 103, in main
ERROR:     !    run_latexmk(filepath)
ERROR:     !  File "/Users/jonathan/.panzer/postflight/latexmk/latexmk.py", line 74, in run_latexmk
ERROR:     !    panzertools.log('ERROR', error)
ERROR:     !  File "/Users/jonathan/.panzer/shared/python/panzertools.py", line 80, in log
ERROR:     !    outgoing_json = json.dumps(outgoing) + '\n'
ERROR:     !  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
ERROR:     !    return _default_encoder.encode(obj)
ERROR:     !  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
ERROR:     !    chunks = self.iterencode(o, _one_shot=True)
ERROR:     !  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
ERROR:     !    return _iterencode(o, 0)
ERROR:     !  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
ERROR:     !    o.__class__.__name__)
ERROR:     !TypeError: Object of type 'FileNotFoundError' is not JSON serializable
          [2/2] /Users/jonathan/.panzer/postflight/open_pdf/open_pdf.py
ERROR:     !297:304: syntax error: Expected end of line but found identifier. (-2741)
```

When I try and run it standalone (``) I get the following short error:
```
`~/.panzer/postflight/latexmk/latexmk.py talk-test.tex
Traceback (most recent call last):
  File "/Users/jonathan/.panzer/postflight/latexmk/latexmk.py", line 11, in <module>
    sys.path.append(os.path.join(os.environ['PANZER_SHARED'], 'python'))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PANZER_SHARED'
```

What should I be doing differently?
